### ISSUE TITLE
MPX template: Replace "PH_CANCOGEN_AUTHORS" with "PH_SEQUENCING_AUTHORS"

### ISSUE THREAD

**Issue by griffie** [cidgoh/pathogen-genomics-package#10]
Found another CanCOGeN artifact in the NML LIMS export from the MPX template.

Can we please replace "PH_CANCOGEN_AUTHORS" with "PH_SEQUENCING_AUTHORS" after the "SUBMITTED_RESLT - Gene Target #5 CT Value" field in the NML export, pretty please?

In the DH template it's supposed to export as "PH_SEQUENCING_AUTHORS" so I'm not sure where "PH_CANCOGEN_AUTHORS" is coming from...

**Comment by ddooley** [comment]
Done, available on next release!
