### ISSUE TITLE
CanCOGeN Template - NML LIMS Export

### ISSUE THREAD

**Issue by GH-Emily** [cidgoh/pathogen-genomics-package#13]
I believe that data entered more than one time in the vaccination fields that are concatenated into the PH_VACCINATION_HISTORY field is getting unintentionally omitted from the NML LIMS dataharmonizer export from the CanCOGeN template. 

When, for example: 

`Astrazeneca (Vaczevria)` is entered for more than one vaccination dose name

the result is: 

`<Host Vaccination Status>;Astrazeneca (Vaxzevria);2022-11-01;2023-01-01;2023-03-01;2023-06-01;<Vaccination History>`

rather than the expected: 

`<Host Vaccination Status>;Astrazeneca (Vaxzevria);2022-11-01;Astrazeneca (Vaxzevria);2023-01-01;Astrazeneca (Vaxzevria);2023-03-01;Astrazeneca (Vaxzevria);2023-06-01;<Vaccination History>`

The same is occurring when the same date is used for one or more vaccination doses.

Thank you!

**Comment by cbarcl01** [comment]
@ddooley - I'm not sure if this has been resolved or not (as the NML LIMS export disappeared for a while), so I'll do some testing and if needed we can push any changes in a later release rather than holding up this one.

**Comment by ddooley** [comment]
These are now fixed in current PGP release!
