### ISSUE TITLE
GRDI Template - isolated_by range is WhiteSpaceMinimizedString, but should be a menu. 

### ISSUE THREAD

**Issue by ejurga** [cidgoh/pathogen-genomics-package#15]
The isolated_by field currently takes a string. However, the same field in the excel template over at the [GRDI_AMR_One_Health](https://github.com/cidgoh/GRDI_AMR_One_Health/blob/c2b9e121206ae06c372cbbf19f1041f6392549dd/Template/GRDI_Harmonization-Template_v9.0.0.xlsm) repo is limited to its own isolated_by menu. This presumably should be incorporated here as well. 

There appears to be an isolated_by menu in the corresponding YAML. I might suggest that, instead of having its own menu, this field take the same menu as sample_collected_by.

**Comment by cbarcl01** [comment]
@ejurga - this should be resolved with the most recent PGP. I'm going to add this over at [GRDI/issues](https://github.com/cidgoh/GRDI_AMR_One_Health/issues) for easier tracking for release notes as well. Thanks for bringing up!

**Comment by cbarcl01** [comment]
@ddooley this has been resolved in the most recent PGP release and can be closed.
