### ISSUE TITLE
Term AGRO:00000080 coded twice under different names under field environmental_material. 

### ISSUE THREAD

**Issue by ejurga** [cidgoh/pathogen-genomics-package#17]
- Pig manure [AGRO:00000080]:
     - text: Pig manure [AGRO:00000080]
     - is_a: Animal manure [AGRO:00000079]

and: 

- Poultry litter [AGRO:00000080]:
    - text: Poultry litter [AGRO:00000080]

Poultry litter is the correct one: http://purl.obolibrary.org/obo/AGRO_00000080

**Comment by cbarcl01** [comment]
@ejurga I've copied this to the GRDI repo issues tab.

**Comment by cbarcl01** [comment]
Resolved as part of [PGPv5.5.0](https://github.com/cidgoh/pathogen-genomics-package/releases/tag/PGPv5.5.0)
