### ISSUE TITLE
PGP 5.3.3 - MPOX Template

### ISSUE THREAD

**Issue by GH-Emily** [cidgoh/pathogen-genomics-package#18]
Hi all! 

Upon review of the PGP 5.3.3 MPOX template, I've come across a few things: 

1. the MPOX template doesn't seem to show the Export To -> NML LIMS option. 
2. the `host age` field allows for values > 130 despite that being set as the maximum_value in the schema (screen shot below)

![image](https://github.com/user-attachments/assets/6837282f-e85e-4071-a15d-cbebe60a6e4a)

3. the `sequencing date` allows for values > today  

![image](https://github.com/user-attachments/assets/707ee251-100c-4299-a8af-b8b8c639b768)

**Comment by ddooley** [comment]
Thanks for reporting this.  First, about no NML Lims export option - I think that option is now available in the latest DataHarmonizer for the "Mpox" template (but not for MpoxInternational).  Working on the other issues you encountered now.

**Comment by ddooley** [comment]
Host age and sequencing date sensitivity to today are fixed now in DataHarmonizer master branch and will be included in the upcoming PHP 5.4.0 release.

**Comment by ddooley** [comment]
This is now in live package so closing.
