### ISSUE TITLE
Syntax errors

### ISSUE THREAD

**Issue by 4jtlin** [cidgoh/pathogen-genomics-package#19]
Hello, in the process of checking internal templates, I came across errors that are also be present in the DataHarmonizer's data standards.

For your consideration, 
1) Purpose of Sampling - "... sample was collected for **d**iagnostic testing ..." - the d should be lowercase. 
Relevant templates: canada_covid19, grdi, influenza, pathogen

2) Collection Method - "... collect the sample e.g. phlebot**o**my..." - it should be an "o" instead of an "a."
Relevant tempaltes: ambr, canada_covid19, influenza, mpox, pathogen

Thank you for your time!

**Comment by cbarcl01** [comment]
Thes changes have been made in the relevant DH templates and will be updated in following releases.

**Comment by cbarcl01** [comment]
Resolved as part of [PGPv5.5.0](https://github.com/cidgoh/pathogen-genomics-package/releases/tag/PGPv5.5.0)
