### ISSUE TITLE
Pathogen Genomics Package "Get latest release" needs to be updated (goes to DH repo)

### ISSUE THREAD

**Issue by griffie** [cidgoh/pathogen-genomics-package#2]
If you open your instance of the PGP and click on "Get latest release" under the Help button, it takes you to the latest DH release (in the DH repo), not the latest release in the PGP repo.

e.g.
Go into pathogen-genomics-package-PGPv1.3.7 data harmonizer
and clicked "get latest release"
and it took me to here:https://github.com/cidgoh/DataHarmonizer/releases
but shouldn't it be going here: https://github.com/cidgoh/pathogen-genomics-package/releases

Can we update please?

**Comment by ddooley** [comment]
Fixed on master now.  Will be included in next release.
