### ISSUE TITLE
Validation Errors in GRDI Template in DataHarmonizer PGP 5.5.0

### ISSUE THREAD

**Issue by cbarcl01** [cidgoh/pathogen-genomics-package#22]
Hi @ddooley - here is the summary of the issue as discussed today:

## Description
A few validation errors have been identified in the GRDI template of the DataHarmonizer tool in pathogen genomics package version 5.5.0.

After testing, its seems these issues have been around for a long time, with the most recent release to not experience this is PGP version 4.1.2, which is DataHarmonizer version 1.6.4

## Issues

**1. Validation errors for valid terms in dropdown fields.** Existing datasets that are opened in the DH are flagged as invalid. There appears to be leading whitespace in the dataset that may be contributing. Affected fields:
- Geo_loc_name (state/province/region)
- Host (common name)
- Antmicrobial_resistance_phenotype: Errors specifically for the enum value 'Intermediate antimicrobial phenotype [ARO:3004300]'.

**2. Recurrent validation errors**. After correcting errors in one column using the latest version's picklist and revalidating, errors reappear in the same column if corrections are made in another column

Affected Versions:

First observed in DataHarmonizer version 1.6.5 with PGP package 5.0.0.

**Comment by cbarcl01** [comment]
Here is a link to the dataset that was shared to test (I'm not sure of this data is to be shared so the access is private to you, let me know if you have any issues).

**Comment by ddooley** [comment]
This is now fixed in DataHarmonizer draft so it will be included in next release, 2.0.0
