### ISSUE TITLE
AMBR template: new release request

### ISSUE THREAD

**Issue by griffie** [cidgoh/pathogen-genomics-package#7]
Some fields have been removed, others added. New picklists have been added. Ontology IDs have been added. Guidance and examples have been updated.

Can we do a new release of the AMBR template pretty please?

I tracked the changes in the version tracker and bumped the proposed version number to 2.1.1 (in red) as there were changes to fields (x), terms (y) and guidance/defs/IDs (z).

**Comment by ddooley** [comment]
Completed last month!
