### ISSUE TITLE
CanCOGeN template: new field and export reqs for NML LIMS 

### ISSUE THREAD

**Issue by griffie** [cidgoh/pathogen-genomics-package#8]
I added a new field called "travel history availability" and values.

Can the values from this field be added to those that are concatenated in the NML LIMS field "PH_TRAVEL" in the NML LIMS export, pretty please?

And then can we do a new release (at the same time as the AMBR release maybe?)? I bumped the template version to 2.1.2 (in red) because there were changes to fields, terms and guidance/examples. 

I suggested bumping the PGP version to 2.0.1 (in red) as there were no new templates added (x), no new schemas (y), but there were changes to existing templates (z).

**Comment by ddooley** [comment]
Completed last month!
