### ISSUE TITLE
MPX template: remove LIMS export field "PH_INSTRUMENT_CGN"

### ISSUE THREAD

**Issue by griffie** [cidgoh/pathogen-genomics-package#9]
In the CanCOGeN DH template, the sequencing instrument information is supposed to export to PH_INSTRUMENT_CGN field whereas the MPX template exports sequencing instrument to PH_INSTRUMENT. 

For some reason both are showing up in the MPX export. Can we turn off the "PH_INSTRUMENT_CGN" field in the MPX export? 

I'm not even sure how that field is showing up since it's not in the MPX template's LIMS export column at all...

**Comment by ddooley** [comment]
So the DataHarmonizer mapping for monkeypox shows that "sequencing instrument" for both canadian and international templates should export to PH_SEQUENCING_INSTRUMENT , which should get tacked onto end of fields.  I can see previously there would have been an empty PH_INSTRUMENT_CGN field, and I have taken that out.  I have ordered PH_SEQUENCING_INSTRUMENT to take its place.  
This will be available on next release.
